### ISSUE TITLE
button text not centered horizontally

### ISSUE THREAD

**Issue by jasoncostello** [codecov/codecov-marketing#14]
the text in the buttons is a few pixels high. it should be (optically) horizontally centered.

<img width="227" alt="screen shot 2018-08-21 at 2 52 30 pm" src="https://user-images.githubusercontent.com/416727/44431419-a80b1500-a552-11e8-8d28-88b23e734d10.png">

should be: 

<img width="342" alt="screen shot 2018-08-21 at 3 00 05 pm" src="https://user-images.githubusercontent.com/416727/44431486-eacced00-a552-11e8-9872-21466af7605a.png">

**Comment by thomasrockhu** [comment]
fixed via https://github.com/codecov/codecov-marketing/commit/80f4051ed7e905706b22b1395fd3c19cf68c5b44
