### ISSUE TITLE
Site container

### ISSUE THREAD

**Issue by jasoncostello** [codecov/codecov-marketing#16]
On large screens, the content of the sections expands greatly and breaks the layout. I suggest a common container utility that has a max-width somewhere around 1550px. It could be used on the main header and nav section, as well as the footer also.

**Comment by thomasrockhu** [comment]
:+1:

**Comment by thomasrockhu** [comment]
fixed via https://github.com/codecov/codecov-marketing/commit/b8ade47276566e47c128058d2222111b18a30073
