### ISSUE TITLE
Homepage missing gradient

### ISSUE THREAD

**Issue by jasoncostello** [codecov/codecov-marketing#17]
The homepage is missing the gradient. If it's troublesome try putting it on the body element. If it's still giving you trouble, ping me and I'll cut a branch and try to get a PR in for you.

**Comment by thomasrockhu** [comment]
nope, this was a fail on my end.  I had a CSS error

**Comment by thomasrockhu** [comment]
fixed via https://github.com/codecov/codecov-marketing/commit/11d75483e845c04f0bb8613c9c4277ffad24a991
