### ISSUE TITLE
Nav and buttons font-weight

### ISSUE THREAD

**Issue by jasoncostello** [codecov/codecov-marketing#18]
The font-weight on the main nav items, footer items, and button text should be Sailec Medium (a weight between regular and bold). 

This requires importing the additional font asset, but you only need to import Sailec Medium and not the italic (there will never be italic nav items).

It's is a very particular detail but it's one I'd like to see implemented. However, I could see the argument against this if the additional font assets makes for a large font bundle. In that case, it might be worth considering excluding the light weight, as it's less likely to be used.

**Comment by thomasrockhu** [comment]
fixed via https://github.com/codecov/codecov-marketing/commit/537bd4baa193d0ef3fef6e7a9c7f223d33186afc
